const ACTION_TYPES = {
  MOVE_TO_NEXT_ITEM: 'MOVE_TO_NEXT_ITEM' as 'MOVE_TO_NEXT_ITEM',
  MOVE_TO_FIRST_ITEM: 'MOVE_TO_FIRST_ITEM' as 'MOVE_TO_FIRST_ITEM',
  MOVE_TO_SECOND_ITEM: 'MOVE_TO_SECOND_ITEM' as 'MOVE_TO_SECOND_ITEM',
  MOVE_TO_THIRD_ITEM: 'MOVE_TO_THIRD_ITEM' as 'MOVE_TO_THIRD_ITEM',
  MOVE_TO_FORTH_ITEM: 'MOVE_TO_FORTH_ITEM' as 'MOVE_TO_FORTH_ITEM'
};

export { ACTION_TYPES };