const CONSTANTS = {
  SCROLL_TO_REFERENCE: 'SCROLL_TO_REFERENCE',
  SET_JAVASCRIPT_OFFSET_TOP: 'SET_JAVASCRIPT_OFFSET_TOP',
  SET_TYPESCRIPT_OFFSET_TOP: 'SET_TYPESCRIPT_OFFSET_TOP',
  GENERAL_OFFSET: 100,
};

export default CONSTANTS;
