const SCROLL_TO_JAVASCRIPT = 'SCROLL_TO_JAVASCRIPT';
const SCROLL_TO_TYPESCRIPT = 'SCROLL_TO_TYPESCRIPT';
const SCROLL_TO_REACT = 'SCROLL_TO_REACT';
const SCROLL_TO_GRAPHQL = 'SCROLL_TO_GRAPHQL';

const SET_JAVASCRIPT_OFFSET_TOP = 'SET_JAVASCRIPT_OFFSET_TOP';
const SET_TYPESCRIPT_OFFSET_TOP = 'SET_TYPESCRIPT_OFFSET_TOP';
const SET_REACT_OFFSET_TOP = 'SET_REACT_OFFSET_TOP';
const SET_GRAPHQL_OFFSET_TOP = 'SET_GRAPHQL_OFFSET_TOP';

const TOPBAR_HEIGHT = 80;

export {
  SCROLL_TO_JAVASCRIPT,
  SCROLL_TO_TYPESCRIPT,
  SCROLL_TO_REACT,
  SCROLL_TO_GRAPHQL,
  SET_JAVASCRIPT_OFFSET_TOP,
  SET_TYPESCRIPT_OFFSET_TOP,
  SET_REACT_OFFSET_TOP,
  SET_GRAPHQL_OFFSET_TOP,
  TOPBAR_HEIGHT
}